#https://docs.spring.io/spring-boot/docs/1.3.3.RELEASE/reference/html/howto-properties-and-configuration.html
server:
  port: 5000

---
spring:
  profiles: prod
server:
  port: 7070

---
spring:
  profiles: test
server:
  port: 4000

